import type { Metadata } from "next"
import { Geist as FontSans } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "PDF Summarizer",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "font-sans antialiased mx-auto selection:text-darkBlue selection:bg-greyBlue",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
